### ISSUE TITLE
Rio500 driver download link missing

### ISSUE THREAD

**Issue by squelch41** [ladipro/rio500#1]
Hi,
I was looking for the rio500 driver - the wiki text implies that there was a link to it but it isnt implemented

"As far as I know, no 64-bit Windows driver has ever been released for this device. Worry not, the driver is available for download here. It is based on the Generic USB Driver DDK sample, "

**Comment by ladipro** [comment]
Hi, I have updated the page with the link. The driver is available here:
https://github.com/ladipro/rio500/releases/tag/1.0.0
